
services:
  tr1s-aid01:
    image: ratio1/edge_node:testnet
    container_name: tr1s-aid01
    restart: always
    volumes:
      - nodes_naeural_01:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  tr1s-aid02:
    image: ratio1/edge_node:testnet
    container_name: tr1s-aid02
    restart: always
    volumes:
      - nodes_naeural_02:/edge_node/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60 # Check every 1 minute
      - WATCHTOWER_CHECK_NEW_IMAGES=true      
      - WATCHTOWER_LABEL_ENABLE=true          

volumes:
  nodes_naeural_01:
    external: true      
  nodes_naeural_02:
    external: true
